version: "3.8"
services:
  mysql:
    container_name: sample-mysql8
    image: mysql:8
    platform: linux/amd64
    restart: always
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
#      - "./mysql/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    env_file: ./mysql/env
    environment:
      TZ: Asia/Seoul
    command: mysqld --innodb_use_native_aio=0
  web:
    container_name: sample-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
  spring:
    container_name: sample-spring
    build: .
    ports:
      - 8080:8080
