apiVersion: v1
kind: Service
metadata:
  name: kotlin-springboot-skeleton-skf
  labels:
    name: kotlin-springboot-skeleton-skf
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kotlin-springboot-skeleton-skf
  type: LoadBalancer
