spring:
  profiles:
    group:
      local: local

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  default-produces-media-type: application/json
