spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test2
#    username: sa
#    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      data-locations: classpath:data-h2.sql
#      mode: always
